---
- name: Check nginx service is running
  become: true
  service:
    name: nginx
    state: started
- name: Unpack deploy files
  unarchive:
    src: "{{deploy_file}}"
    dest: "/var/www/html"
    owner: "{{user}}"
    group: "{{group}}"