---
- name: Install Applications
  apt:
    update_cache: yes
    pkg:
    - nginx

  environment:
    ACCEPT_EULA: 'y'
    state: present

- name: copy Nginx main config file from role's default, if necessary
  template:
    src:  config-files/conf.d/voice-web.conf
    dest: /etc/nginx/sites-available/default
  notify:
    - reload nginx
