---
- name: Install Applications
  apt:
    update_cache: yes
    pkg:
    - nginx

  environment:
    ACCEPT_EULA: 'y'
    state: present

# - name: Copy config files for nginx
#   copy:
#     src: config-files/{{item}}
#     dest: /etc/nginx/
#     owner: root
#     group: root
#     mode: 0644
#   with_items:
#   - nginx.conf

- name: copy Nginx main config file from role's default, if necessary
  template:
    src:  config-files/conf.d/web-organizese.j2
    # dest: /etc/nginx/conf.d/default.conf
    dest: /etc/nginx/sites-available/default
    # validate: "nginx -t -c %s"
  # when: nginx_conf_main is not defined
  notify:
    - reload nginx
